name: Calls custom_action_sandbox
on:
  push:

jobs:
  provision_resources:
    runs-on: ubuntu-latest
    name: Calls custom_action_sandbox
    steps:
      - id: custom_action_sandbox_caller
        uses: jlieow/custom_action_sandbox@V1 
        with:
          terraform_env_variables: |
            key=value,
            test=this,
            hello=world
            